# https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

[build.environment]
  GO_VERSION = "1.20"
  HUGO_VERSION = "0.115.1"

[[headers]]
  for = "/*"
  [headers.values]
	Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[redirects]]
  from = "/"
  to = "/blog"
  status = 200